### ISSUE TITLE
Upgrading to latest Caveman Tools results in errors in SqlFu

### ISSUE THREAD

**Issue by ahazelwood** [sapiens/SqlFu#84]
System.MissingMethodException: Method not found: 'Void System.AssertionsExtensions.MustNotBeEmpty(System.String, System.String)'.
   at SqlFu.SqlFuConnection.Init(String cnxString, IHaveDbProvider provider)
   at SqlFu.SqlFuConnection..ctor(String connectionStringName) in e:\Projects.Net\SqlFu\src\SqlFu\SqlFuConnection.cs:line 29

**Comment by sapiens** [comment]
Right.... CavemanTools 4 is for SqlFu 3. I will update the SqlFu 2 nuget to reflect that it works only with CTools v3.

**Comment by ahazelwood** [comment]
Thanks, hopefully that will save some grief for some other people.
